### ISSUE TITLE
Bug: Nearby list is showing players from other zones via other players sent data.

### ISSUE THREAD

**Issue by Everydejavu** [pretoast/Spy#3]
I was thinking have it only report MY detected players as a value at first but with Spy adding players found by group/guild too maybe just set to players found in same zone? https://i.imgur.com/x5nu6aS.jpg The real count in this screencap should be 5.

**Comment by pretoast** [comment]
The players from other zones showing up in the Nearby list is something I see as a bug that Spy has had for a while. I plan to add in a zone check to make sure that doesn't happen.

**Comment by pretoast** [comment]
Fixed so that the nearby player list only will show players that are in the same zone as you.
